# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 15:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamingChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creation date')),
                ('modification_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Modification date')),
                ('delete_date', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Delete date')),
                ('description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Description')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/channel_icons', verbose_name='Channel icon')),
                ('url', models.URLField(verbose_name='URL streaming channel')),
                ('owner_user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='channels', to=settings.AUTH_USER_MODEL, verbose_name='Owner streaming channels')),
            ],
            options={
                'verbose_name_plural': 'Streaming channels',
                'permissions': (),
                'verbose_name': 'Streaming channel',
            },
        ),
    ]
