# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-20 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamingchannel',
            name='name',
            field=models.CharField(default='tv3', max_length=25, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
